{
  "hash": "cf8a578823af8e87d8a36d4246464625",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Project Title\"\nsubtitle: \"INFO 526 - Summer 2025 - Final Project\"\nauthor: \n  - name: \"Yashi Mi & Nathan Herling\"\n    affiliations:\n      - name: \"School of Information, University of Arizona\"\ndescription: \"Project description\"\nformat:\n  html:\n    code-tools: true\n    code-overflow: wrap\n    code-line-numbers: true\n    embed-resources: true\n    css: slide_styles.css\n    code-fold: true\neditor: visual\nexecute:\n  warning: false\n  echo: false\n---\n\n\n\n\n## Abstract\nPlumbing insecurity—a critical dimension of water insecurity—refers to households lacking complete indoor plumbing, with significant implications for public health, hygiene, and infrastructure equity. While often taken for granted in developed countries, inadequate access to safe indoor plumbing elevates the risk of waterborne diseases, impedes hygiene, and disproportionately affects vulnerable populations across income levels. Tracking plumbing insecurity helps identify emerging public health risks, guide resource allocation, and inform equitable infrastructure development. This study analyzes U.S. county-level plumbing insecurity using 2022–2023 ACS data, employing bar plots, choropleth maps, and spatial clustering (Getis-Ord G) to detect geographic hotspots and coldspots. Using a Queen contiguity method with a 20 km snap distance and a Z-score threshold of 1.96, we analyzed 673 counties for spatial clustering. Results identified hotspot clusters of worsening conditions primarily in New Jersey, Louisiana, and Michigan, while coldspot clusters showing improvement were most concentrated in Virginia and Ohio. Persistent regional disparities remain, with plumbing insecurity concentrated in Arizona and New Mexico—especially Apache, McKinley, and Navajo counties—as well as notable insecurity in Alaska’s Fairbanks North Star and Matanuska-Susitna counties, highlighting ongoing infrastructural challenges and the need for targeted policy interventions.\n\n## Question 1:\n\n::: scientific-box\nTop counties had the highest plumbing insecurity in 2022 and 2023?\n:::\n\n### Introduction\n\n<br>These two datasets provide information on the lack of complete indoor plumbing across U.S. counties in 2022 and 2023. The 2022 dataset includes data from 848 counties, while the 2023 dataset covers 854 counties, reflecting increased reporting in 2023. Each dataset contains seven variables: county ID (geoid), county name, geographic boundaries (geometry), year, total population, number of households lacking plumbing, and the percent lacking plumbing. This analysis focuses on identifying the top counties with the highest plumbing insecurity in each year and examining the geographic distribution of these counties to understand regional patterns of indoor plumbing leakage in the United States.<br>\n\n### Approach\n\n<br>We will identify and visualize the U.S. counties with the highest levels of plumbing insecurity in 2022 and 2023. We first cleaned the data using the dplyr package by sorting counties in descending order of percent lacking plumbing and selecting the top 10 counties. We then created a new variable to classify counties as having greater than 1% or less than 1% plumbing insecurity for color coding in plots. For visualization, we used ggplot2 to create bar graphs displaying the top 10 counties with the highest plumbing insecurity percentages in 2022 and 2023, colored by insecurity level. To visualize the geographic distribution, we loaded a U.S. county shapefile using the tigris package (the geometry information in the datasets were stored as character class strings rather than usable spatial geometry objects), merged it with our top 10 data by county geoid, and created a choropleth map.<br>\n\n### Analysis\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# - loading package manager\nif (!require(pacman))\n  install.packages(pacman)\n\n# - loading required packages\npacman::p_load(tidyverse,\n               here,\n               forcats,\n               scales,\n               sf,\n               tidycensus,\n               tigris,\n               ggrepel,\n               viridis,\n               spdep,\n               tmap\n               )\n\nlibrary(tidyverse)\nlibrary(here)\nlibrary(patchwork)\nlibrary(viridis)    # for turbo colors\nlibrary(ggrepel)    # for repel annotations\n\noptions(readr.show_progress = FALSE)\noptions(tigris_progress = FALSE)\nsf::sf_use_s2(FALSE)      # optional, disables spherical geometry engine, may help\noptions(sf.show_progress = FALSE)  # this is the key\n# This suppresses CLI (command line interface) output from certain packages,\n# especially those using the 'cli' package (like dplyr, tidyr, etc.).\n# By setting cli.default_handler to a function that does nothing (`invisible()`),\n# it silences progress bars, messages, and styled output from these packages.\noptions(cli.default_handler = function(...) invisible())\n\n# This tells the 'tigris' package (used for downloading U.S. Census boundary data)\n# to cache shapefiles locally. This speeds up future runs by avoiding repeated downloads.\n# The shapefiles are stored in a cache directory on your machine.\noptions(tigris_use_cache = TRUE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Load water insecurity data from the TidyTuesday project (2025-01-28)\n# This dataset explores social vulnerability and access to complete indoor\n# plumbing across U.S. counties,\n# curated by Niha Pereira and featured in the blog post:\n# \"Mapping water insecurity in R with tidycensus\"\n# Original data sources include the U.S. Census Bureau (ACS) and the USGS Vizlab’s\n# “Unequal Access to Water” visualization.\n# Repo: \n# https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-01-28\nsuppressMessages(water_insecurity_2022 <- read_csv(here(\"water_insecurity\",\n                                       \"water_insecurity_2022.csv\"),progress = FALSE))\nsuppressMessages(water_insecurity_2023 <- read_csv(here(\"water_insecurity\",\n                                       \"water_insecurity_2023.csv\"),progress = FALSE))\nglimpse(water_insecurity_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 848\nColumns: 7\n$ geoid                    <chr> \"01069\", \"04001\", \"06037\", \"06097\", \"06001\", …\n$ name                     <chr> \"Houston County, Alabama\", \"Apache County, Ar…\n$ year                     <dbl> 2022, 2022, 2022, 2022, 2022, 2022, 2022, 202…\n$ geometry                 <chr> \"list(list(c(975267.980555021, 975512.9445474…\n$ total_pop                <dbl> 108079, 65432, 9721138, 482650, 1628997, 8978…\n$ plumbing                 <dbl> 93, 2440, 6195, 148, 808, 18, 128, 0, 123, 13…\n$ percent_lacking_plumbing <dbl> 0.08604817, 3.72906223, 0.06372711, 0.0306640…\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nglimpse(water_insecurity_2023)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 854\nColumns: 7\n$ geoid                    <chr> \"01003\", \"01069\", \"06037\", \"06087\", \"06097\", …\n$ name                     <chr> \"Baldwin County, Alabama\", \"Houston County, A…\n$ year                     <dbl> 2023, 2023, 2023, 2023, 2023, 2023, 2023, 202…\n$ geometry                 <chr> \"list(list(c(765297.99052762, 765703.76567671…\n$ total_pop                <dbl> 253507, 108462, 9663345, 261547, 481812, 1155…\n$ plumbing                 <dbl> 271, 30, 5248, 187, 308, 517, 4, 198, 1269, 8…\n$ percent_lacking_plumbing <dbl> 0.106900401, 0.027659457, 0.054308317, 0.0714…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nTop10_2022<-water_insecurity_2022 |>\n  arrange(desc(percent_lacking_plumbing))|>\n  slice_head(n = 10)|>\n  mutate(name = fct_reorder(name, percent_lacking_plumbing),\n         percentage = case_when(percent_lacking_plumbing > 1 ~ \"> 1%\",\n         TRUE ~ \"≤ 1%\"))\nglimpse(Top10_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10\nColumns: 8\n$ geoid                    <chr> \"04001\", \"35031\", \"04017\", \"02090\", \"04005\", …\n$ name                     <fct> \"Apache County, Arizona\", \"McKinley County, N…\n$ year                     <dbl> 2022, 2022, 2022, 2022, 2022, 2022, 2022, 202…\n$ geometry                 <chr> \"list(list(c(-1229881.12883199, -1229880.9118…\n$ total_pop                <dbl> 65432, 69830, 108650, 95356, 144060, 113325, …\n$ plumbing                 <dbl> 2440, 1941, 1759, 1239, 1700, 950, 551, 534, …\n$ percent_lacking_plumbing <dbl> 3.7290622, 2.7796076, 1.6189600, 1.2993414, 1…\n$ percentage               <chr> \"> 1%\", \"> 1%\", \"> 1%\", \"> 1%\", \"> 1%\", \"≤ 1%…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(Top10_2022, aes(y=name, x=percent_lacking_plumbing, fill = percentage))+\n  geom_col()+\n  scale_fill_manual(\n    values = c(\"> 1%\" = \"#E76F51\", \"≤ 1%\" = \"#2A9D8F\"))+\n  labs(\n    title = \"Top 10 U.S. Counties with Highest Plumbing Insecurity (2022)\",\n    x = \"Lacking Plumbing\",\n    y = \"\"\n  ) +\n  scale_x_continuous(labels = label_percent(scale = 1))+\n  theme_minimal()+\n   theme(\n     panel.grid = element_blank(),\n     plot.margin = margin(t = 5, r = 20, b = 5, l = -20)  # top, right, bottom, left//.. shift it left\n     )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/graph-q1-1-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nTop10_2023<-water_insecurity_2023 |>\n  arrange(desc(percent_lacking_plumbing))|>\n  slice_head(n = 10)|>\n  mutate(name = fct_reorder(name, percent_lacking_plumbing),\n         percentage = case_when(percent_lacking_plumbing > 1 ~ \"> 1%\",\n         TRUE ~ \"≤ 1%\"))\nglimpse(Top10_2023)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10\nColumns: 8\n$ geoid                    <chr> \"04001\", \"35031\", \"02090\", \"04017\", \"04005\", …\n$ name                     <fct> \"Apache County, Arizona\", \"McKinley County, N…\n$ year                     <dbl> 2023, 2023, 2023, 2023, 2023, 2023, 2023, 202…\n$ geometry                 <chr> \"list(list(c(-1229881.12883199, -1229880.9118…\n$ total_pop                <dbl> 65036, 68797, 94840, 109175, 144472, 71888, 1…\n$ plumbing                 <dbl> 2545, 1585, 1786, 2019, 1390, 682, 1083, 434,…\n$ percent_lacking_plumbing <dbl> 3.9132173, 2.3038795, 1.8831717, 1.8493245, 0…\n$ percentage               <chr> \"> 1%\", \"> 1%\", \"> 1%\", \"> 1%\", \"≤ 1%\", \"≤ 1%…\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/graph-q1-2-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ncounties_sf <- counties(cb = TRUE, year = 2022, class = \"sf\")\n\ncounties_top10_2022 <- counties_sf |>\n  left_join(Top10_2022, by = c(\"GEOID\" = \"geoid\"))\n\nglimpse(counties_top10_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,235\nColumns: 20\n$ STATEFP                  <chr> \"01\", \"01\", \"01\", \"01\", \"01\", \"04\", \"04\", \"05…\n$ COUNTYFP                 <chr> \"069\", \"023\", \"005\", \"107\", \"033\", \"012\", \"00…\n$ COUNTYNS                 <chr> \"00161560\", \"00161537\", \"00161528\", \"00161580…\n$ AFFGEOID                 <chr> \"0500000US01069\", \"0500000US01023\", \"0500000U…\n$ GEOID                    <chr> \"01069\", \"01023\", \"01005\", \"01107\", \"01033\", …\n$ NAME                     <chr> \"Houston\", \"Choctaw\", \"Barbour\", \"Pickens\", \"…\n$ NAMELSAD                 <chr> \"Houston County\", \"Choctaw County\", \"Barbour …\n$ STUSPS                   <chr> \"AL\", \"AL\", \"AL\", \"AL\", \"AL\", \"AZ\", \"AZ\", \"AR…\n$ STATE_NAME               <chr> \"Alabama\", \"Alabama\", \"Alabama\", \"Alabama\", \"…\n$ LSAD                     <chr> \"06\", \"06\", \"06\", \"06\", \"06\", \"06\", \"06\", \"06…\n$ ALAND                    <dbl> 1501742235, 2365900083, 2292160151, 228283504…\n$ AWATER                   <dbl> 4795415, 19114321, 50523213, 22621093, 791603…\n$ name                     <fct> NA, NA, NA, NA, NA, NA, \"Apache County, Arizo…\n$ year                     <dbl> NA, NA, NA, NA, NA, NA, 2022, NA, NA, NA, NA,…\n$ geometry.y               <chr> NA, NA, NA, NA, NA, NA, \"list(list(c(-1229881…\n$ total_pop                <dbl> NA, NA, NA, NA, NA, NA, 65432, NA, NA, NA, NA…\n$ plumbing                 <dbl> NA, NA, NA, NA, NA, NA, 2440, NA, NA, NA, NA,…\n$ percent_lacking_plumbing <dbl> NA, NA, NA, NA, NA, NA, 3.729062, NA, NA, NA,…\n$ percentage               <chr> NA, NA, NA, NA, NA, NA, \"> 1%\", NA, NA, NA, N…\n$ geometry.x               <MULTIPOLYGON [°]> MULTIPOLYGON (((-85.71209 3..., …\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() +\n  geom_sf(data = counties_sf, fill = \"grey90\", color = \"white\") +   \n  geom_sf(data = counties_top10_2022, aes(fill = percentage), color = NA) + \n  scale_fill_manual(\n    values = c(\"> 1%\" = \"#E76F51\", \"≤ 1%\" = \"#2A9D8F\"),na.value = NA,) +\n  labs(\n    title = \"Top 10 U.S. Counties with Highest Plumbing Insecurity (2022)\") +\n  coord_sf(xlim = c(-180, -60), ylim = c(15, 72)) + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/graph-q1-3-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ncounties_sf <- counties(cb = TRUE, year = 2022, class = \"sf\")\ncounties_top10_2023 <- counties_sf |>\n  left_join(Top10_2023, by = c(\"GEOID\" = \"geoid\"))\nglimpse(counties_top10_2023)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,235\nColumns: 20\n$ STATEFP                  <chr> \"01\", \"01\", \"01\", \"01\", \"01\", \"04\", \"04\", \"05…\n$ COUNTYFP                 <chr> \"069\", \"023\", \"005\", \"107\", \"033\", \"012\", \"00…\n$ COUNTYNS                 <chr> \"00161560\", \"00161537\", \"00161528\", \"00161580…\n$ AFFGEOID                 <chr> \"0500000US01069\", \"0500000US01023\", \"0500000U…\n$ GEOID                    <chr> \"01069\", \"01023\", \"01005\", \"01107\", \"01033\", …\n$ NAME                     <chr> \"Houston\", \"Choctaw\", \"Barbour\", \"Pickens\", \"…\n$ NAMELSAD                 <chr> \"Houston County\", \"Choctaw County\", \"Barbour …\n$ STUSPS                   <chr> \"AL\", \"AL\", \"AL\", \"AL\", \"AL\", \"AZ\", \"AZ\", \"AR…\n$ STATE_NAME               <chr> \"Alabama\", \"Alabama\", \"Alabama\", \"Alabama\", \"…\n$ LSAD                     <chr> \"06\", \"06\", \"06\", \"06\", \"06\", \"06\", \"06\", \"06…\n$ ALAND                    <dbl> 1501742235, 2365900083, 2292160151, 228283504…\n$ AWATER                   <dbl> 4795415, 19114321, 50523213, 22621093, 791603…\n$ name                     <fct> NA, NA, NA, NA, NA, NA, \"Apache County, Arizo…\n$ year                     <dbl> NA, NA, NA, NA, NA, NA, 2023, NA, NA, NA, NA,…\n$ geometry.y               <chr> NA, NA, NA, NA, NA, NA, \"list(list(c(-1229881…\n$ total_pop                <dbl> NA, NA, NA, NA, NA, NA, 65036, NA, NA, NA, NA…\n$ plumbing                 <dbl> NA, NA, NA, NA, NA, NA, 2545, NA, NA, NA, NA,…\n$ percent_lacking_plumbing <dbl> NA, NA, NA, NA, NA, NA, 3.913217, NA, NA, NA,…\n$ percentage               <chr> NA, NA, NA, NA, NA, NA, \"> 1%\", NA, NA, NA, N…\n$ geometry.x               <MULTIPOLYGON [°]> MULTIPOLYGON (((-85.71209 3..., …\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() +\n  geom_sf(data = counties_sf, fill = \"grey90\", color = \"white\") +   \n  geom_sf(data = counties_top10_2023, aes(fill = percentage), color = NA) + \n  scale_fill_manual(\n    values = c(\"> 1%\" = \"#E76F51\", \"≤ 1%\" = \"#2A9D8F\"),na.value = NA,) +\n  labs(\n    title = \"Top 10 U.S. Counties with Highest Plumbing Insecurity (2023)\") +\n  coord_sf(xlim = c(-180, -60), ylim = c(15, 72)) + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/graph-q1-4-1.png){width=672}\n:::\n:::\n\n\n\n\n### Discussion\n\n<br>Both the 2022 and 2023 maps show that Arizona and New Mexico counties dominate the highest plumbing insecurity group (\\>1%), suggesting persistent disparities in plumbing access across the Southwest. Among these two states, Apache County (Arizona), McKinley County (New Mexico), and Navajo County (Arizona) consistently ranked among the top four counties with the highest plumbing insecurity in both years, indicating enduring infrastructure and access challenges in these regions. Additionally, Alaska counties, including Fairbanks North Star Borough and Matanuska-Susitna Borough, consistently appeared with notable insecurity levels, highlighting infrastructure limitations in remote areas. Overall, plumbing insecurity in the U.S. remains concentrated in specific Southwestern and Alaskan counties, reflecting long-standing infrastructural inequities in these regions.<br>\n\n## Question 2:\n\n::: scientific-box\nHow did the plumbing insecurity change from 2022 to 2023 across U.S. counties, and where do significant spatial clusters (hotspots and coldspots) of worsening or improving plumbing access exist?\n:::\n\n### Introduction\n\nThis analysis examines how plumbing insecurity has changed across U.S. counties between 2022 and 2023. Plumbing insecurity is defined as the percentage of households lacking complete indoor plumbing, a key indicator of basic water access. Using data from the American Community Survey (ACS), we aim to measure the year-over-year change in plumbing access and determine whether there are spatial clusters—groups of neighboring counties—that have significantly improved (coldspots) or worsened (hotspots). The 2022 dataset includes 848 counties, while the 2023 dataset includes 854 counties. For this analysis, we restrict the data to counties that are present in both years and have no missing values for the percent_lacking_plumbing variable, allowing for a valid and consistent change calculation.\n\n### Approach\n\nAfter cleaning and filtering the data to retain only counties with complete plumbing insecurity data for both 2022 and 2023, we calculated the year-over-year change in plumbing insecurity as the difference in percentages between the two years. To explore spatial patterns in these changes, we performed Local Getis-Ord G* analysis using the spdep package, which identifies statistically significant local clusters of high or low values within geographic neighborhoods.\n\nTo visualize these spatial clusters, we created a choropleth map using the tmap package. This map colors counties based on their hotspot, coldspot, or non-significant status, providing an intuitive spatial overview of where plumbing insecurity is worsening or improving. Choropleth maps are ideal for this purpose because they convey geographic patterns clearly and facilitate regional comparisons.\n\nIn addition to the spatial visualization, we conducted a hyperparameter sweep across key model parameters—specifically snap distance and contiguity type—to understand how these choices affect the detection of spatial clusters. This analysis was visualized using a line plot showing the number and significance of identified clusters as a function of snap distance. The line plot helps illustrate how parameter tuning impacts model sensitivity and potential overfitting, making it easier to select optimal settings for reliable spatial inference.\n\nTogether, these two complementary plots — a choropleth map and a hyperparameter sweep line plot — allow us to both identify meaningful spatial patterns in plumbing insecurity change and validate the robustness of our spatial clustering methodology.\n\n::: scientific-box2\n<b>Spatial Cluster Classification</b><br>\n\n<p>Each county was labeled based on the Getis-Ord <em>G\\*</em> z-score as follows:</p>\n\n<ul>\n\n<li><strong>Hotspot</strong> (significantly worsening): <code>z ≥ 1.96</code></li>\n\n<li><strong>Coldspot</strong> (significantly improving): <code>z ≤ -1.96</code></li>\n\n<li><strong>Not significant</strong> (no spatial clustering): <code>-1.96 \\< z \\< 1.96</code></li>\n\n</ul>\n\n<p>These classifications were used to identify clusters of counties with statistically meaningful changes in plumbing insecurity between 2022 and 2023.</p>\n:::\n\n### Analysis\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# ────────────────────────────────────────────────\n# Load hyperparameter sweep results\nresults_tbl <- read_csv(here(\"_extra\", \"hyper_param_sweep.csv\"), show_col_types = FALSE)\n\n# ────────────────────────────────────────────────\n# Shared plot theme\nbase_theme <- theme_minimal(base_size = 13)\n\n# ────────────────────────────────────────────────\n# Set cutoff for significance\nz_cutoff <- 1.96\n\n# ────────────────────────────────────────────────\n# Define shading colors from viridis turbo palette\nshade_hot_color <- viridis(10, option = \"turbo\")[7]  # bright yellow-ish\nshade_cold_color <- viridis(10, option = \"turbo\")[4] # teal-ish\n\n# ────────────────────────────────────────────────\n# Hotspot plot (positive z)\np_hotspot <- ggplot(\n  results_tbl %>% filter(!is.na(`Hotspot (Worsening)`)),\n  aes(x = z, y = `Hotspot (Worsening)`, color = factor(snap))\n) +\n  # Shade right of cutoff line (zone of significance)\n  annotate(\n    \"rect\",\n    xmin = z_cutoff, xmax = Inf,\n    ymin = -Inf, ymax = Inf,\n    fill = shade_hot_color,\n    alpha = 0.7\n  ) +\n  geom_line(linewidth = 1) +\n  facet_wrap(~ queen, labeller = label_both) +\n  geom_vline(xintercept = z_cutoff, linetype = \"dashed\", color = \"red\") +\n  # Repel annotation for vertical line\n  geom_text_repel(\n    data = tibble(\n      x = z_cutoff,\n      y = max(results_tbl$`Hotspot (Worsening)`, na.rm = TRUE) * 0.3,\n      label = paste0(\"z = \", z_cutoff)\n    ),\n    aes(x = x, y = y, label = label),\n    color = \"black\",\n    nudge_x = -0.32,\n    nudge_y = -0.4 * max(results_tbl$`Hotspot (Worsening)`, na.rm = TRUE),\n    direction = \"y\",\n    hjust = 1,\n    segment.size = 0.3,\n    segment.color = \"grey50\",\n    size = 4\n  ) +\n  annotate(\n    \"text\",\n    x = z_cutoff + 0.2,\n    y = max(results_tbl$`Hotspot (Worsening)`, na.rm = TRUE) * 0.8,\n    label = \"Statistical Significance\\nHotspots (p ≤ 0.05)\",\n    color = \"black\",\n    hjust = 0.21,\n    size = 3\n  ) +\n  labs(\n    title = \"Hotspot Counts vs Positive Z-Threshold\",\n    x = \"Z-Threshold\",\n    y = \"Hotspot Count\",\n    color = \"Snap Distance\"\n  ) +\n  base_theme +\n  theme(\n    panel.spacing.x = unit(1.5, \"lines\"),  # increased horizontal spacing\n    strip.text = element_text(size = 12, face = \"bold\"),  # Larger & bold facet titles\n    plot.title = element_text(hjust = 0.5)\n    )\n\n# ────────────────────────────────────────────────\n# Coldspot plot (negative z)\ncoldspot_data <- results_tbl %>%\n  filter(!is.na(`Coldspot (Improving)`)) %>%\n  mutate(z_neg = -z)\n\np_coldspot <- ggplot(\n  coldspot_data,\n  aes(x = z_neg, y = `Coldspot (Improving)`, color = factor(snap))\n) +\n  # Shade left of cutoff line (zone of significance)\n  annotate(\n    \"rect\",\n    xmin = -Inf, xmax = -z_cutoff,\n    ymin = -Inf, ymax = Inf,\n    fill = shade_cold_color,\n    alpha = 0.7\n  ) +\n  geom_line(linewidth = 1) +\n  facet_wrap(~ queen, labeller = label_both) +\n  geom_vline(xintercept = -z_cutoff, linetype = \"dashed\", color = \"red\") +\n  # Repel annotation for vertical line\n  geom_text_repel(\n    data = tibble(\n      x = -z_cutoff,\n      y = max(coldspot_data$`Coldspot (Improving)`, na.rm = TRUE) * 0.3,\n      label = paste0(\"z = -\", z_cutoff)\n    ),\n    aes(x = x, y = y, label = label),\n    color = \"black\",\n    nudge_x = 0.3,\n    nudge_y = -0.5 * max(coldspot_data$`Coldspot (Improving)`, na.rm = TRUE),\n    direction = \"y\",\n    hjust = 0,\n    segment.size = 0.3,\n    segment.color = \"grey50\",\n    size = 4\n  ) +\n  annotate(\n    \"text\",\n    x = -z_cutoff - 0.2,\n    y = max(coldspot_data$`Coldspot (Improving)`, na.rm = TRUE) * 0.85,\n    label = \"Statistical Significance\\nColdspots (p ≤ 0.05)\",\n    color = \"black\",\n    hjust = 0.82,\n    size = 3\n  ) +\n  labs(\n    title = \"Coldspot Counts vs Negative Z-Threshold\",\n    x = \"Z-Threshold (Negative for Coldspots)\",\n    y = \"Coldspot Count\",\n    color = \"Snap Distance\"\n  ) +\n  base_theme +\n  theme(\n    panel.spacing.x = unit(1.5, \"lines\"),  # increased horizontal spacing\n    strip.text = element_text(size = 12, face = \"bold\"),  # Larger & bold facet titles\n    plot.title = element_text(hjust = 0.5)\n  )\n# ────────────────────────────────────────────────\n# Combine plots vertically with equal heights\ncombined_plot <- p_hotspot / p_coldspot + plot_layout(heights = c(1, 1))\n\n# ────────────────────────────────────────────────\n# Save and print\nggsave(\n  filename = here(\"_extra\", \"topo_lines_hotspot_coldspot_shaded_annotated.png\"),\n  plot = combined_plot,\n  width = 8,\n  height = 10\n)\n\nprint(combined_plot)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/label-me-code-block-5-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# ────────────────────────────────────────────────\n# Hyperparameters\nqueen_setting <- TRUE\nsnap_distance <- 20000\nz_threshold <- 1.96\n\n# ────────────────────────────────────────────────\n# Load and clean data\nwater_2022_clean <- read.csv(here(\"Water_insecurity\", \"water_insecurity_2022.csv\")) %>%\n  filter(!is.na(percent_lacking_plumbing)) %>%\n  mutate(geoid = as.character(geoid))\n\nwater_2023_clean <- read.csv(here(\"Water_insecurity\", \"water_insecurity_2023.csv\")) %>%\n  filter(!is.na(percent_lacking_plumbing)) %>%\n  mutate(geoid = as.character(geoid))\n\n# Filter to common GEOIDs\ncommon_geoids <- intersect(water_2022_clean$geoid, water_2023_clean$geoid)\nwater_2022_filtered <- water_2022_clean %>% filter(geoid %in% common_geoids)\nwater_2023_filtered <- water_2023_clean %>% filter(geoid %in% common_geoids)\n\n# ────────────────────────────────────────────────\n# Join to shapefile\ncounties_sf <- counties(cb = TRUE, year = 2022, class = \"sf\")\n\n# Filter to continental US counties (exclude AK '02', HI '15', PR '72', etc.)\ncontinental_states <- setdiff(unique(counties_sf$STATEFP), c(\"02\", \"15\", \"72\"))\ncounties_sf_continental <- counties_sf %>%\n  filter(STATEFP %in% continental_states)\n\ntotal_counties_continental <- nrow(counties_sf_continental)\n\ncounties_2022 <- counties_sf_continental %>%\n  left_join(water_2022_filtered %>%\n              select(geoid, percent_lacking_plumbing_2022 = percent_lacking_plumbing),\n            by = c(\"GEOID\" = \"geoid\"))\n\ncounties_2023 <- counties_sf_continental %>%\n  left_join(water_2023_filtered %>%\n              select(geoid, percent_lacking_plumbing),\n            by = c(\"GEOID\" = \"geoid\"))\n\n# ────────────────────────────────────────────────\n# Calculate change and project\nspatial_data <- counties_2023 %>%\n  left_join(counties_2022 %>% st_drop_geometry() %>%\n              select(GEOID, percent_lacking_plumbing_2022),\n            by = \"GEOID\") %>%\n  mutate(change = percent_lacking_plumbing - percent_lacking_plumbing_2022) %>%\n  filter(!is.na(change))\n\n# Project to Albers Equal Area\nspatial_data <- st_transform(spatial_data, crs = 5070)\n\n# ────────────────────────────────────────────────\n# Create neighbors\nnb <- poly2nb(spatial_data, queen = queen_setting, snap = snap_distance)\n\n# Identify and exclude counties with no neighbors\nno_neighbors <- which(card(nb) == 0)\nnum_no_neighbors <- length(no_neighbors)\n\nif (num_no_neighbors > 0) {\n  spatial_data <- spatial_data[-no_neighbors, ]\n  nb <- poly2nb(spatial_data, queen = queen_setting, snap = snap_distance)\n}\n\n# Total counties analyzed after exclusions\ntotal_analyzed <- nrow(spatial_data)\n\n# ────────────────────────────────────────────────\n# Print alert summary\ncat(\n  \"Summary:\\n\",\n  \"Total counties in continental US: \", total_counties_continental, \"\\n\",\n  \"Counties excluded due to missing neighbors: \", num_no_neighbors, \"\\n\",\n  \"Total counties analyzed: \", total_analyzed, \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSummary:\n Total counties in continental US:  3122 \n Counties excluded due to missing neighbors:  50 \n Total counties analyzed:  673 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# ────────────────────────────────────────────────\n# Create spatial weights\nlw <- nb2listw(nb, style = \"W\", zero.policy = TRUE)\n\n# Compute Local G* statistic\nlocal_gstar <- localG(spatial_data$change, listw = lw, zero.policy = TRUE)\nspatial_data$gstar_z <- as.numeric(local_gstar)\n\n# ────────────────────────────────────────────────\n# Classify clusters based on z-score thresholds\nspatial_data <- spatial_data %>%\n  mutate(cluster_type = case_when(\n    gstar_z >=  z_threshold  ~ \"Hotspot (Worsening)\",\n    gstar_z <= -z_threshold  ~ \"Coldspot (Improving)\",\n    TRUE                     ~ \"Not Significant\"\n  ))\n\n# ────────────────────────────────────────────────\n# Count clusters for annotation and update labels\ncluster_counts <- spatial_data %>%\n  count(cluster_type) %>%\n  complete(cluster_type = c(\"Hotspot (Worsening)\", \"Coldspot (Improving)\", \"Not Significant\"), fill = list(n = 0))\n\ncluster_labels <- cluster_counts %>%\n  mutate(label = paste0(cluster_type, \" [n=\", n, \"]\")) %>%\n  arrange(factor(cluster_type, levels = c(\"Hotspot (Worsening)\", \"Coldspot (Improving)\", \"Not Significant\"))) %>%\n  pull(label)\n\n# Update cluster_type to factor with counts in labels\nspatial_data$cluster_type <- factor(spatial_data$cluster_type,\n                                    levels = c(\"Hotspot (Worsening)\", \"Coldspot (Improving)\", \"Not Significant\"),\n                                    labels = cluster_labels)\n\n# ────────────────────────────────────────────────\n# Set tmap mode and create the final plot\ntmap_mode(\"plot\")\n\ncluster_colors <- c(\n  \"#FDE725FF\",\n  \"#21908CFF\",\n  \"#440154FF\"\n)\nnames(cluster_colors) <- cluster_labels\n\n# ────────────────────────────────────────────────\n# Get state boundaries for overlay\nstates_sf <- states(cb = TRUE, year = 2022, class = \"sf\") %>%\n  filter(STATEFP %in% continental_states) %>%\n  st_transform(crs = st_crs(spatial_data))  # match CRS with spatial_data\n\n# ────────────────────────────────────────────────\n# Add overlay to existing plot\ng1 <- tm_shape(spatial_data) +\n  tm_polygons(\"cluster_type\",\n              fill.scale = tm_scale(values = cluster_colors,\n                                    legend.title = \"Plumbing Access Change Clusters\")) +\n  tm_shape(states_sf) +  # overlay begins here\n  tm_borders(lwd = 1.2, col = \"black\") +\n  tm_title(\"Spatial Clustering of Plumbing Access Changes (2022–2023)\", size = 1.2) +\n  tm_credits(\n    paste0(\n      \"Local G* Statistic (z ≥ ±\", z_threshold, \")\\n\",\n      \"Contiguity = \", ifelse(queen_setting, \"Queen\", \"Rook\"),\n      \" | Snap Distance = \", snap_distance, \" meters\"\n    ),\n    position = c(\"center\", \"top\"),\n    size = 0.7,\n    lines = 2\n  ) +\n  tm_layout(\n    legend.position = c(\"left\", \"bottom\"),\n    legend.just = \"right\",\n    legend.outside = FALSE,\n    legend.text.size = 0.6,\n    legend.title.size = 0.75,\n    inner.margins = c(0.2, 0.02, 0.12, 0.02)\n  )\n\nprint(g1)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/label-me-code-block-6-1.png){width=672}\n:::\n:::\n\n\n\n<h5>A .gif animation showing hot/cold spot analysis for hyperparamter sweep of 'Snap Distance'</h5>\n<div style=\"max-width: 800px; margin: 0 auto; text-align: center;\">\n  <img src=\"images/snap_distance_sweep.gif\" style=\"width: 100%; max-width: 800px;\" />\n</div>\n\n\n\n\n---\ntitle: \"Analysis Summary\"\nformat: html\n---\n\n\n\n::: {.table-wrapper style=\"background:#f5f7fa; border:1px solid #007BFF; padding:10px; border-radius:8px; margin:25px;\"}\n##### Table 1: Data Summary for machine learning parameters.\n| Category                  | Details                                    |\n|---------------------------|--------------------------------------------|\n| **Contiguity Method**     | Queen                                      |\n| **Snap Distance**         | 20000 meters                               |\n| **Z-Score Threshold**     | 1.96                                       |\n| **Total counties (continental US)** | 3122                           |\n| **Counties excluded (no neighbors)** | 50                            |\n| **Counties analyzed**     | 673                                        |\n:::\n\n::: {.table-wrapper style=\"background:#f5f7fa; border:1px solid #007BFF; padding:10px; border-radius:8px; margin:25px; font-size:0.75em;\"}\n##### Table 2: Hotspot Counties (Worsening) by State (Most counties first)\n\n| State        | Number of Counties (n)                      |\n|--------------|:------------------------------------------:|\n| New Jersey   | 3                                          |\n| Louisiana    | 2                                          |\n| Michigan     | 2                                          |\n| Delaware     | 2                                          |\n| Florida      | 1                                          |\n| Kansas       | 1                                          |\n| Missouri     | 1                                          |\n| Pennsylvania | 1                                          |\n| South Carolina | 1                                        |\n| Texas        | 1                                          |\n\n:::\n\n\n::: {.table-wrapper style=\"background:#f5f7fa; border:1px solid #007BFF; padding:10px; border-radius:8px; margin:25px; font-size:0.75em;\"}\n\n##### Table 3: Coldspot Counties (Improving) by State (Most counties first)\n\n| <span style=\"font-size:1.2em;\">State</span>        | <span style=\"font-size:1.2em;\">Number of Counties (n)</span>                      |\n|--------------|:------------------------------------------:|\n| Virginia     | 8                                          |\n| Ohio         | 4                                          |\n| Pennsylvania | 2                                          |\n| Florida      | 2                                          |\n| Louisiana    | 1                                          |\n| Texas        | 1                                          |\n| Illinois     | 1                                          |\n| Kentucky     | 1                                          |\n| New Mexico   | 1                                          |\n| South Carolina | 1                                        |\n| Washington   | 1                                          |\n:::\n\n\n\n### Discussion\n\nThe choropleth map of Getis-Ord G* clusters reveals that year-over-year changes in plumbing insecurity are not randomly distributed across U.S. counties but are instead spatially patterned. Statistically significant hotspots—areas where plumbing access worsened—were most concentrated in New Jersey, Louisiana, and Michigan, while coldspots—areas of improvement—were primarily found in Virginia and Ohio. These patterns likely reflect regional differences in infrastructure funding, policy implementation, or socioeconomic vulnerability.\n\nTo evaluate how spatial model parameters interacted with the data’s topology, a hyperparameter sweep was performed across three variables: contiguity type (Queen vs. Rook), snap distance, and z-score threshold. Among these, snap distance had the most substantial impact on the clustering results. A 20,000-meter threshold produced coherent clusters without overfitting, while higher distances led to overly broad neighborhood definitions and reduced spatial precision. The Queen contiguity setting—capturing both shared edges and corners—was used, but contiguity type had minimal influence on output quality. The z-score threshold of ±1.96 (p ≤ 0.05) effectively distinguished statistically significant clusters.\n\nThese findings demonstrate that significant clusters of change in plumbing insecurity do exist and are geographically meaningful—but only when spatial model parameters are carefully tuned. The hyperparameter sweep, akin to methods used in machine learning, revealed that snap distance was the most influential factor in detecting these patterns. When set too high, the model effectively overfit, diluting meaningful local trends by merging unrelated counties into large, unrealistic neighborhoods. By selecting an optimal 20 km threshold, we improved model interpretability and spatial resolution without compromising statistical validity. This outcome highlights the value of treating spatial analysis with the same rigor applied in machine learning workflows—where thoughtful parameter tuning is essential to uncovering accurate and actionable insights.\n\n### Video Link\n#### Watch the presentation?\n<div style=\"text-align: center; margin-top: 1em;\">\n  <a href=\"https://arizona.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c1deeff3-49aa-488e-8fa5-b30f0100e035\" target=\"_blank\" style=\"text-decoration: none;\">\n    <img src=\"images/water_drop_2.png\" alt=\"Watch Video\" style=\"width: 300px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2); transition: transform 0.2s;\">\n    <div style=\"margin-top: 0.5em; font-weight: bold; color: #2c3e50;\">Watch Video</div>\n  </a>\n</div>\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}