project:
  type: website
  output-dir: docs  # 👈 ADD THIS LINE
  resources:
    - images

website:
  title: Project Title
  description: "Project for INFO 526 - Data Visualization and Analysis at The University of Arizona, Summer 2025."
  site-url: "https://n-herling-mk1.github.io/project-final/"

  favicon: /images/water_drop_4.png
  navbar:
    right:
      - icon: github
        href: https://github.com/N-Herling-Mk1/project-final # Needs to be changed to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true


execute:
  freeze: auto

