<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yashi Mi &amp; Nathan Herling">
<meta name="description" content="Project description">

<title>Analysis Summary – Project Title</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href=".//images/water_drop_4.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f3c2ea88cadbcfb37ba28ffa2c97cfc1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-ae2d0dcda2edce4ab590422bb373b64f.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Project Title</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html"> 
<span class="menu-text">Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.html"> 
<span class="menu-text">Presentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/N-Herling-Mk1/project-final"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1:</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2:</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  <li><a href="#approach-1" id="toc-approach-1" class="nav-link" data-scroll-target="#approach-1">Approach</a></li>
  <li><a href="#analysis-1" id="toc-analysis-1" class="nav-link" data-scroll-target="#analysis-1">Analysis</a></li>
  <li><a href="#discussion-1" id="toc-discussion-1" class="nav-link" data-scroll-target="#discussion-1">Discussion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis Summary</h1>
<p class="subtitle lead">INFO 526 - Summer 2025 - Final Project</p>
</div>

<div>
  <div class="description">
    Project description
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Yashi Mi &amp; Nathan Herling </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            School of Information, University of Arizona
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Plumbing insecurity—a critical dimension of water insecurity—refers to households lacking complete indoor plumbing, with significant implications for public health, hygiene, and infrastructure equity. While often taken for granted in developed countries, inadequate access to safe indoor plumbing elevates the risk of waterborne diseases, impedes hygiene, and disproportionately affects vulnerable populations across income levels. Tracking plumbing insecurity helps identify emerging public health risks, guide resource allocation, and inform equitable infrastructure development. This study analyzes U.S. county-level plumbing insecurity using 2022–2023 ACS data, employing bar plots, choropleth maps, and spatial clustering (Getis-Ord G) to detect geographic hotspots and coldspots. Using a Queen contiguity method with a 20 km snap distance and a Z-score threshold of 1.96, we analyzed 673 counties for spatial clustering. Results identified hotspot clusters of worsening conditions primarily in New Jersey, Louisiana, and Michigan, while coldspot clusters showing improvement were most concentrated in Virginia and Ohio. Persistent regional disparities remain, with plumbing insecurity concentrated in Arizona and New Mexico—especially Apache, McKinley, and Navajo counties—as well as notable insecurity in Alaska’s Fairbanks North Star and Matanuska-Susitna counties, highlighting ongoing infrastructural challenges and the need for targeted policy interventions.</p>
</section>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1:</h2>
<div class="scientific-box">
<p>Top counties had the highest plumbing insecurity in 2022 and 2023?</p>
</div>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p><br><b>These two datasets provide information on the lack of complete indoor plumbing across U.S. counties in 2022 and 2023. The 2022 dataset includes data from 848 counties, while the 2023 dataset covers 854 counties, reflecting increased reporting in 2023. Each dataset contains seven variables: county ID (geoid), county name, geographic boundaries (geometry), year, total population, number of households lacking plumbing, and the percent lacking plumbing. This analysis focuses on identifying the top counties with the highest plumbing insecurity in each year and examining the geographic distribution of these counties to understand regional patterns of indoor plumbing leakage in the United States.</b><br></p>
</section>
<section id="approach" class="level3">
<h3 class="anchored" data-anchor-id="approach">Approach</h3>
<p><br><b>We will identify and visualize the U.S. counties with the highest levels of plumbing insecurity in 2022 and 2023. We first cleaned the data using the dplyr package by sorting counties in descending order of percent lacking plumbing and selecting the top 10 counties. We then created a new variable to classify counties as having greater than 1% or less than 1% plumbing insecurity for color coding in plots. For visualization, we used ggplot2 to create bar graphs displaying the top 10 counties with the highest plumbing insecurity percentages in 2022 and 2023, colored by insecurity level. To visualize the geographic distribution, we loaded a U.S. county shapefile using the tigris package (the geometry information in the datasets were stored as character class strings rather than usable spatial geometry objects), merged it with our top 10 data by county geoid, and created a choropleth map.</b><br></p>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 848
Columns: 7
$ geoid                    &lt;chr&gt; "01069", "04001", "06037", "06097", "06001", …
$ name                     &lt;chr&gt; "Houston County, Alabama", "Apache County, Ar…
$ year                     &lt;dbl&gt; 2022, 2022, 2022, 2022, 2022, 2022, 2022, 202…
$ geometry                 &lt;chr&gt; "list(list(c(975267.980555021, 975512.9445474…
$ total_pop                &lt;dbl&gt; 108079, 65432, 9721138, 482650, 1628997, 8978…
$ plumbing                 &lt;dbl&gt; 93, 2440, 6195, 148, 808, 18, 128, 0, 123, 13…
$ percent_lacking_plumbing &lt;dbl&gt; 0.08604817, 3.72906223, 0.06372711, 0.0306640…</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 854
Columns: 7
$ geoid                    &lt;chr&gt; "01003", "01069", "06037", "06087", "06097", …
$ name                     &lt;chr&gt; "Baldwin County, Alabama", "Houston County, A…
$ year                     &lt;dbl&gt; 2023, 2023, 2023, 2023, 2023, 2023, 2023, 202…
$ geometry                 &lt;chr&gt; "list(list(c(765297.99052762, 765703.76567671…
$ total_pop                &lt;dbl&gt; 253507, 108462, 9663345, 261547, 481812, 1155…
$ plumbing                 &lt;dbl&gt; 271, 30, 5248, 187, 308, 517, 4, 198, 1269, 8…
$ percent_lacking_plumbing &lt;dbl&gt; 0.106900401, 0.027659457, 0.054308317, 0.0714…</code></pre>
</div>
</div>
<div class="cell" data-lable="code-block-1">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 10
Columns: 8
$ geoid                    &lt;chr&gt; "04001", "35031", "04017", "02090", "04005", …
$ name                     &lt;fct&gt; "Apache County, Arizona", "McKinley County, N…
$ year                     &lt;dbl&gt; 2022, 2022, 2022, 2022, 2022, 2022, 2022, 202…
$ geometry                 &lt;chr&gt; "list(list(c(-1229881.12883199, -1229880.9118…
$ total_pop                &lt;dbl&gt; 65432, 69830, 108650, 95356, 144060, 113325, …
$ plumbing                 &lt;dbl&gt; 2440, 1941, 1759, 1239, 1700, 950, 551, 534, …
$ percent_lacking_plumbing &lt;dbl&gt; 3.7290622, 2.7796076, 1.6189600, 1.2993414, 1…
$ percentage               &lt;chr&gt; "&gt; 1%", "&gt; 1%", "&gt; 1%", "&gt; 1%", "&gt; 1%", "≤ 1%…</code></pre>
</div>
</div>
<div class="cell" data-lable="graph-q1-1">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-lable="code-block-2">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 10
Columns: 8
$ geoid                    &lt;chr&gt; "04001", "35031", "02090", "04017", "04005", …
$ name                     &lt;fct&gt; "Apache County, Arizona", "McKinley County, N…
$ year                     &lt;dbl&gt; 2023, 2023, 2023, 2023, 2023, 2023, 2023, 202…
$ geometry                 &lt;chr&gt; "list(list(c(-1229881.12883199, -1229880.9118…
$ total_pop                &lt;dbl&gt; 65036, 68797, 94840, 109175, 144472, 71888, 1…
$ plumbing                 &lt;dbl&gt; 2545, 1585, 1786, 2019, 1390, 682, 1083, 434,…
$ percent_lacking_plumbing &lt;dbl&gt; 3.9132173, 2.3038795, 1.8831717, 1.8493245, 0…
$ percentage               &lt;chr&gt; "&gt; 1%", "&gt; 1%", "&gt; 1%", "&gt; 1%", "≤ 1%", "≤ 1%…</code></pre>
</div>
</div>
<div class="cell" data-lable="graph-q1-2">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<details>
<summary>
Code: Load Library county Data
</summary>
<div class="cell" data-lable="code-block-3">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,235
Columns: 20
$ STATEFP                  &lt;chr&gt; "01", "01", "01", "01", "01", "04", "04", "05…
$ COUNTYFP                 &lt;chr&gt; "069", "023", "005", "107", "033", "012", "00…
$ COUNTYNS                 &lt;chr&gt; "00161560", "00161537", "00161528", "00161580…
$ AFFGEOID                 &lt;chr&gt; "0500000US01069", "0500000US01023", "0500000U…
$ GEOID                    &lt;chr&gt; "01069", "01023", "01005", "01107", "01033", …
$ NAME                     &lt;chr&gt; "Houston", "Choctaw", "Barbour", "Pickens", "…
$ NAMELSAD                 &lt;chr&gt; "Houston County", "Choctaw County", "Barbour …
$ STUSPS                   &lt;chr&gt; "AL", "AL", "AL", "AL", "AL", "AZ", "AZ", "AR…
$ STATE_NAME               &lt;chr&gt; "Alabama", "Alabama", "Alabama", "Alabama", "…
$ LSAD                     &lt;chr&gt; "06", "06", "06", "06", "06", "06", "06", "06…
$ ALAND                    &lt;dbl&gt; 1501742235, 2365900083, 2292160151, 228283504…
$ AWATER                   &lt;dbl&gt; 4795415, 19114321, 50523213, 22621093, 791603…
$ name                     &lt;fct&gt; NA, NA, NA, NA, NA, NA, "Apache County, Arizo…
$ year                     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 2022, NA, NA, NA, NA,…
$ geometry.y               &lt;chr&gt; NA, NA, NA, NA, NA, NA, "list(list(c(-1229881…
$ total_pop                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 65432, NA, NA, NA, NA…
$ plumbing                 &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 2440, NA, NA, NA, NA,…
$ percent_lacking_plumbing &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 3.729062, NA, NA, NA,…
$ percentage               &lt;chr&gt; NA, NA, NA, NA, NA, NA, "&gt; 1%", NA, NA, NA, N…
$ geometry.x               &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-85.71209 3..., …</code></pre>
</div>
</div>
</details>
<div class="cell" data-lable="graph-q1-3">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-lable="code-block-4">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,235
Columns: 20
$ STATEFP                  &lt;chr&gt; "01", "01", "01", "01", "01", "04", "04", "05…
$ COUNTYFP                 &lt;chr&gt; "069", "023", "005", "107", "033", "012", "00…
$ COUNTYNS                 &lt;chr&gt; "00161560", "00161537", "00161528", "00161580…
$ AFFGEOID                 &lt;chr&gt; "0500000US01069", "0500000US01023", "0500000U…
$ GEOID                    &lt;chr&gt; "01069", "01023", "01005", "01107", "01033", …
$ NAME                     &lt;chr&gt; "Houston", "Choctaw", "Barbour", "Pickens", "…
$ NAMELSAD                 &lt;chr&gt; "Houston County", "Choctaw County", "Barbour …
$ STUSPS                   &lt;chr&gt; "AL", "AL", "AL", "AL", "AL", "AZ", "AZ", "AR…
$ STATE_NAME               &lt;chr&gt; "Alabama", "Alabama", "Alabama", "Alabama", "…
$ LSAD                     &lt;chr&gt; "06", "06", "06", "06", "06", "06", "06", "06…
$ ALAND                    &lt;dbl&gt; 1501742235, 2365900083, 2292160151, 228283504…
$ AWATER                   &lt;dbl&gt; 4795415, 19114321, 50523213, 22621093, 791603…
$ name                     &lt;fct&gt; NA, NA, NA, NA, NA, NA, "Apache County, Arizo…
$ year                     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 2023, NA, NA, NA, NA,…
$ geometry.y               &lt;chr&gt; NA, NA, NA, NA, NA, NA, "list(list(c(-1229881…
$ total_pop                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 65036, NA, NA, NA, NA…
$ plumbing                 &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 2545, NA, NA, NA, NA,…
$ percent_lacking_plumbing &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 3.913217, NA, NA, NA,…
$ percentage               &lt;chr&gt; NA, NA, NA, NA, NA, NA, "&gt; 1%", NA, NA, NA, N…
$ geometry.x               &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-85.71209 3..., …</code></pre>
</div>
</div>
<div class="cell" data-lable="graph-q1-4">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<p><br><b>Both the 2022 and 2023 maps show that Arizona and New Mexico counties dominate the highest plumbing insecurity group (&gt;1%), suggesting persistent disparities in plumbing access across the Southwest. Among these two states, Apache County (Arizona), McKinley County (New Mexico), and Navajo County (Arizona) consistently ranked among the top four counties with the highest plumbing insecurity in both years, indicating enduring infrastructure and access challenges in these regions. Additionally, Alaska counties, including Fairbanks North Star Borough and Matanuska-Susitna Borough, consistently appeared with notable insecurity levels, highlighting infrastructure limitations in remote areas. Overall, plumbing insecurity in the U.S. remains concentrated in specific Southwestern and Alaskan counties, reflecting long-standing infrastructural inequities in these regions.</b><br></p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2:</h2>
<div class="scientific-box">
<p>How did the plumbing insecurity change from 2022 to 2023 across U.S. counties, and where do significant spatial clusters (hotspots and coldspots) of worsening or improving plumbing access exist?</p>
</div>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">Introduction</h3>
<p>This analysis examines how plumbing insecurity has changed across U.S. counties between 2022 and 2023. Plumbing insecurity is defined as the percentage of households lacking complete indoor plumbing, a key indicator of basic water access. Using data from the American Community Survey (ACS), we aim to measure the year-over-year change in plumbing access and determine whether there are spatial clusters—groups of neighboring counties—that have significantly improved (coldspots) or worsened (hotspots). The 2022 dataset includes 848 counties, while the 2023 dataset includes 854 counties. For this analysis, we restrict the data to counties that are present in both years and have no missing values for the percent_lacking_plumbing variable, allowing for a valid and consistent change calculation.</p>
</section>
<section id="approach-1" class="level3">
<h3 class="anchored" data-anchor-id="approach-1">Approach</h3>
<p>We cleaned and filtered the 2022 and 2023 datasets using the dplyr package to remove rows with missing percent_lacking_plumbing values and retained only counties with data available in both years. We then computed a new variable: plumbing_change, calculated as the 2023 percentage minus the 2022 percentage. This measure captures whether plumbing access improved (negative change) or worsened (positive change) from year to year.</p>
<p>To detect spatial patterns in these changes, we performed Local Getis-Ord G analysis* using the spdep package. This statistical method identifies local clusters of high or low values within a geographic neighborhood, helping us evaluate whether counties with similar changes in plumbing access are geographically grouped. We defined a spatial weights matrix based on county adjacency and calculated Local G* z-scores to identify statistically significant clusters.</p>
<div class="scientific-box2">
<p><b>Spatial Cluster Classification</b><br></p>
<p>
Each county was labeled based on the Getis-Ord <em>G*</em> z-score as follows:
</p>
<ul>
<li>
<strong>Hotspot</strong> (significantly worsening): <code>z ≥ 1.96</code>
</li>
<li>
<strong>Coldspot</strong> (significantly improving): <code>z ≤ -1.96</code>
</li>
<li>
<strong>Not significant</strong> (no spatial clustering): <code>-1.96 &lt; z &lt; 1.96</code>
</li>
</ul>
<p>
These classifications were used to identify clusters of counties with statistically meaningful changes in plumbing insecurity between 2022 and 2023.
</p>
</div>
<p>To visualize the spatial clustering, we used the tmap package to create a color-coded choropleth map of the continental U.S., with counties shaded by cluster classification. This allowed us to see where plumbing insecurity is improving or deteriorating in a spatially meaningful way.</p>
<p>As a secondary strategy (to be used if spatial significance was limited), we planned a backup approach: identifying counties with a relative change of ±10% or more. This allows us to capture substantial shifts even if they are not spatially clustered.</p>
</section>
<section id="analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="analysis-1">Analysis</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/label-me-code-block-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Summary:
 Total counties in continental US:  3122 
 Counties excluded due to missing neighbors:  50 
 Total counties analyzed:  673 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/label-me-code-block-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div style="max-width: 800px; margin: 0 auto;">
<p><img src="images/snap_distance_sweep.gif" style="width: 100%;"></p>
</div>
<div class="salmon-box">
<p><br><b>#ToDo</b><br></p>
</div>
</section>
<section id="discussion-1" class="level3">
<h3 class="anchored" data-anchor-id="discussion-1">Discussion</h3>
<section id="table-1-data-summary-for-machine-learning-parameters." class="level5 table-wrapper" style="background:#f5f7fa; border:1px solid #007BFF; padding:10px; border-radius:8px; margin:25px;">
<h5 class="anchored" data-anchor-id="table-1-data-summary-for-machine-learning-parameters.">Table 1: Data Summary for machine learning parameters.</h5>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Contiguity Method</strong></td>
<td>Queen</td>
</tr>
<tr class="even">
<td><strong>Snap Distance</strong></td>
<td>20000 meters</td>
</tr>
<tr class="odd">
<td><strong>Z-Score Threshold</strong></td>
<td>1.96</td>
</tr>
<tr class="even">
<td><strong>Total counties (continental US)</strong></td>
<td>3122</td>
</tr>
<tr class="odd">
<td><strong>Counties excluded (no neighbors)</strong></td>
<td>50</td>
</tr>
<tr class="even">
<td><strong>Counties analyzed</strong></td>
<td>673</td>
</tr>
</tbody>
</table>
</section>
<section id="table-2-hotspot-counties-worsening-by-state-most-counties-first" class="level5 table-wrapper" style="background:#f5f7fa; border:1px solid #007BFF; padding:10px; border-radius:8px; margin:25px;">
<h5 class="anchored" data-anchor-id="table-2-hotspot-counties-worsening-by-state-most-counties-first">Table 2: Hotspot Counties (Worsening) by State (Most counties first)</h5>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th><span style="font-size:1.2em;">State</span></th>
<th style="text-align: center;"><span style="font-size:1.2em;">Number of Counties (n)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>New Jersey</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td>Louisiana</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td>Michigan</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td>Delaware</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td>Florida</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td>Kansas</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td>Missouri</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td>Pennsylvania</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td>South Carolina</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td>Texas</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</section>
<section id="table-3-coldspot-counties-improving-by-state-most-counties-first" class="level5 table-wrapper" style="background:#f5f7fa; border:1px solid #007BFF; padding:10px; border-radius:8px; margin:25px;">
<h5 class="anchored" data-anchor-id="table-3-coldspot-counties-improving-by-state-most-counties-first">Table 3: Coldspot Counties (Improving) by State (Most counties first)</h5>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th><span style="font-size:1.2em;">State</span></th>
<th style="text-align: center;"><span style="font-size:1.2em;">Number of Counties (n)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Virginia</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td>Ohio</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td>Pennsylvania</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td>Florida</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td>Louisiana</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td>Texas</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td>Illinois</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td>Kentucky</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td>New Mexico</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td>South Carolina</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td>Washington</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</section>
<div class="salmon-box">
<p><br><b>#ToDo</b><br></p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/n-herling-mk1\.github\.io\/project-final\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>